version: '3.8'

services:
  book-rent-api:
    container_name: book-rent-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/bookrentdb
      SPRING_DATASOURCE_USERNAME: bookrentuser
      SPRING_DATASOURCE_PASSWORD: bookrentpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - app-network

  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bookrentdb
      POSTGRES_USER: bookrentuser
      POSTGRES_PASSWORD: bookrentpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
