services:
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: bookrentdb
      POSTGRES_USER: bookrentuser
      POSTGRES_PASSWORD: bookrentpass
    networks:
      - shared-network

  book-rent-api:
    container_name: book-rent-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8007:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/bookrentdb
      SPRING_DATASOURCE_USERNAME: bookrentuser
      SPRING_DATASOURCE_PASSWORD: bookrentpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      KAFKA_BROKERS: kafka:29092
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:29092
      SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS: kafka:29092
    networks:
      - shared-network

networks:
  shared-network:
    external: true
